manifest_version = 2
name = "Tag requests with geolocation data"
description = ""
authors = ["<oss@fastly.com>"]
language = "rust"

[local_server.backends.origin_0]
  url = "https://httpbin.org"

[setup.backends.origin_0]
address = "httpbin.org"
port = 443
